name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y build-essential g++

    - name: Build project
      run: g++ -o prog main.cpp

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: prog-linux
        path: ./prog

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MinGW
      run: choco install mingw

    - name: Add MinGW to PATH
      shell: bash
      run: echo 'C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin' >> $GITHUB_PATH

    - name: Build project (Windows)
      run: g++ -static-libgcc -static-libstdc++ -o prog.exe main.cpp

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: prog-windows
        path: ./prog.exe
