name: C/C++ Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential g++

      - name: Build project
        run: g++ -o kobochki-linux main.cpp

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: kobochki-linux
          path: ./kobochki-linux